# Generated by Django 5.0.1 on 2024-02-05 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_region_nombre_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='sites',
            field=models.ManyToManyField(blank=True, to='app.sitetouristique'),
        ),
        migrations.AlterField(
            model_name='sitetouristique',
            name='nombre_partenaires',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='HoraireOuverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('site_touristique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sitetouristique')),
            ],
        ),
    ]
