# Generated by Django 5.0.1 on 2024-02-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_sitetouristique_horaires_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site_touristique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sitetouristique')),
            ],
        ),
    ]
