# Generated by Django 5.0.1 on 2024-02-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='type_partenaire',
            field=models.CharField(blank=True, choices=[('HOTEL', 'HOTEL'), ('RESTAURANT', 'RESTAURANT')], max_length=60),
        ),
    ]
