# Generated by Django 5.0.1 on 2024-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_partenaire_type_partenaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touriste',
            name='partenaires',
            field=models.ManyToManyField(null=True, to='app.partenaire'),
        ),
    ]
