# Generated by Django 5.0.1 on 2024-02-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_touriste_partenaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='nom_region',
            field=models.CharField(choices=[('MARITIME', 'Maritime'), ('PLATEAUX', 'Plateaux'), ('CENTRALE', 'Centrale'), ('KARA', 'Kara'), ('SAVANES', 'Savanes')], max_length=30),
        ),
    ]
