# Generated by Django 5.0.1 on 2024-02-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_region_nom_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touriste',
            name='partenaires',
            field=models.ManyToManyField(blank=True, null=True, to='app.partenaire'),
        ),
    ]
