# Generated by Django 5.0.1 on 2024-02-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_touriste_partenaires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetouristique',
            name='nombre_partenaires',
        ),
    ]
