# Generated by Django 5.0.1 on 2024-02-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_sitetouristique_nombre_partenaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='partenaires', to='app.sitetouristique'),
        ),
    ]
